<?php

namespace AppBundle\Repository;

//use AppBundle\Entity\Astronauts;
use Doctrine\ORM\EntityRepository;

/**
 * AstronautsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AstronautsRepository extends EntityRepository
{
	
}
